# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FShareDemo' do

pod 'FWeiXinSDK', '~> 0.0.3'
pod 'FTencentSDK', '~> 0.0.2'
pod 'WeiboSDK', '~> 3.1.3'

end
